function migrate_files(dryRun)
%MIGRATE_FILES Move files to organized folder structure
%   migrate_files() - Move files (default: dry run mode)
%   migrate_files(true) - Dry run (show what would be moved)
%   migrate_files(false) - Actually move files
%
%   This script moves files from the root directory to organized folders
%   based on the folder structure plan.

if nargin < 1
    dryRun = true;  % Default to dry run for safety
end

if dryRun
    fprintf('=== DRY RUN MODE - No files will be moved ===\n\n');
else
    fprintf('=== MOVING FILES ===\n\n');
end

%% File mappings: {sourceFile, targetFolder}
% Build fileMappings as a cell array programmatically to avoid concatenation issues
fileMappings = {};

% Training scripts
trainingFiles = {
    'train_model_fixed_overfitting.m', ...
    'compare_loss_functions.m', ...
    'train_vgg16_gradcam.m', ...
    'train_vgg16_lime.m', ...
    'train_vgg16_lime_fixed.m', ...
    'train_vgg16_lime_memory_efficient.m', ...
    'train_vgg16_lime_precomputed.m', ...
    'training_with_precomputed_gradcam.m', ...
    'training_with_precomputed_gradcam.asv', ...
    'kriging_hyperparameter_optimization.m'};
for i = 1:length(trainingFiles)
    fileMappings{end+1} = {trainingFiles{i}, 'src/training'};
end

% Evaluation scripts
evalFiles = {
    'evaluate_with_tta.m', ...
    'evaluate_ood_performance.m', ...
    'evaluate_cam_ood.m', ...
    'evaluate_cam_ood_complete.m', ...
    'test_ood_cam_complete.m', ...
    'test_ood_full_cxr.m', ...
    'test_cam_ood_cxr.m', ...
    'test_vgg16_on_cxr.m'};
for i = 1:length(evalFiles)
    fileMappings{end+1} = {evalFiles{i}, 'src/evaluation'};
end

% Loss functions
lossFiles = {
    'custom_loss_gradcam_advanced.m', ...
    'custom_loss_gradcam_clean.m', ...
    'custom_loss_gradcam_comprehensive.m', ...
    'custom_loss_gradcam_optimized.m', ...
    'custom_loss_gradcam_segmentation_enhanced_fixed.m', ...
    'custom_loss_gradcam_soft_iou_kfold.m', ...
    'custom_loss_gradcam_training.m', ...
    'custom_loss_gradcam_with_mask_iou.m', ...
    'custom_loss_gradcam_with_mask_iou_fast.m', ...
    'Loss_grad_cam.m', ...
    'VGG_loss_lime_entropy.m', ...
    'Resnet50_Loss.m'};
for i = 1:length(lossFiles)
    fileMappings{end+1} = {lossFiles{i}, 'src/loss_functions'};
end

% Visualization scripts
vizFiles = {
    'visualize_gradcam.m', ...
    'generate_research_paper_visualizations.m', ...
    'create_publication_visualizations_fixed.m', ...
    'create_comprehensive_visualizations.m', ...
    'create_comprehensive_visualizations__.m', ...
    'create_key_visualizations.m', ...
    'run_visualizations.m', ...
    'test_visualization_generator.m'};
for i = 1:length(vizFiles)
    fileMappings{end+1} = {vizFiles{i}, 'src/visualization'};
end

% Data preprocessing scripts
preprocFiles = {
    'organize_cxr_images.m', ...
    'organize_cxr_simple.m', ...
    'organize_cxr_with_annotations.m', ...
    'resize_and_copy_to_resized.m', ...
    'resize_and_organize_images.m', ...
    'precompute_gradcams.m', ...
    'create_roi_from_cxr_and_masks.m', ...
    'copy_masks_only.m', ...
    'remove_images_without_masks.m', ...
    'analyze_resized_folder.m', ...
    'run_resize_script.m'};
for i = 1:length(preprocFiles)
    fileMappings{end+1} = {preprocFiles{i}, 'scripts/data_preprocessing'};
end

% Analysis scripts
analysisFiles = {
    'segmentation_mask_similarity_metrics.m', ...
    'vgg16_cam_mask_similarity_metrics.m', ...
    'ssim_based_loss_on_precomputed_gradcam.m', ...
    'ssim_based_loss_on_precomputed_gradcam_2.m', ...
    'ssim_vgg_2.m', ...
    'diagnostic_test.m', ...
    'debug_gradcam.m', ...
    'debug_network.m', ...
    'diagnose_overfitting.m', ...
    'function ablation_and_ood_experiments.m', ...
    'function fast_kfold_segmentation_enhance.m', ...
    'vgg16_custom_loop.m', ...
    'vgg16_custom_loop_loss2.m', ...
    'vgg16_custom_loop_loss3.m', ...
    'vgg16_custom_loop_loss4.m', ...
    'vgg16_roi_entropy_custom_loop.m', ...
    'vgg16_lungs_test.m'};
for i = 1:length(analysisFiles)
    fileMappings{end+1} = {analysisFiles{i}, 'scripts/analysis'};
end

% Documentation - Guides
guideFiles = {
    'TRAINING_RESULTS_ANALYSIS.md', ...
    'OOD_TEST_README.md', ...
    'KRIGING_OPTIMIZATION_README.md', ...
    'RESEARCH_PAPER_VISUALIZATIONS_README.md', ...
    'IMPROVE_OOD_ACCURACY_README.md', ...
    'IMPLEMENTATION_SUMMARY.md', ...
    'README_FOLDER_STRUCTURE.md'};
for i = 1:length(guideFiles)
    fileMappings{end+1} = {guideFiles{i}, 'docs/guides'};
end

% Documentation - Analysis
analysisDocs = {
    'OVERFITTING_ANALYSIS.md', ...
    'ROC_AUC_ANALYSIS.md', ...
    'MEDICAL_IMAGE_AUGMENTATION.md', ...
    'DOMAIN_ADAPTATION_EXPLANATION.md', ...
    'TVERSKY_LOSS_IMPLEMENTATION.md', ...
    'Comprehensive_Kriging_Analysis.md', ...
    'kriging_optimization_analysis.md', ...
    'kriging_results_tables.md', ...
    'kriging_executive_summary.md'};
for i = 1:length(analysisDocs)
    fileMappings{end+1} = {analysisDocs{i}, 'docs/analysis'};
end

% Documentation - Papers
paperDocs = {
    'methodology_1.qmd', ...
    'kriging_latex_format.tex', ...
    'latex_figure_descriptions.md', ...
    'RESEARCH_COMPLETION_PLAN.md', ...
    'FOLDER_STRUCTURE_PLAN.md'};
for i = 1:length(paperDocs)
    fileMappings{end+1} = {paperDocs{i}, 'docs/papers'};
end

% Models - Pretrained
modelFiles = {
    'vgg16_finetuned_on_roi.mat', ...
    'vgg16_trained_on_roi.m', ...
    'custom_cnn_and_vgg16_gradcam_mask_iou.mat'};
for i = 1:length(modelFiles)
    fileMappings{end+1} = {modelFiles{i}, 'models/pretrained'};
end

% Other files (to be reviewed)
otherFiles = {
    'custom.m', ...
    'custom.asv', ...
    'custom_lime.m', ...
    'custom_lime.asv', ...
    'custom_roi.m', ...
    'custom_vgg16_transfer_gradcam.m', ...
    'cnn_lime.asv', ...
    'code_1.m', ...
    'fast_simple_test.m', ...
    'fine_tuned_lime.m', ...
    'improve_ood_accuracy.m', ...
    'simple_fixed_comprehensive.m', ...
    'block_diagram_vgg16.m', ...
    'workflow.m', ...
    'workflow_diagram.m', ...
    'run_diagram.m', ...
    'custom_loss_gradcam_wireframe.svg', ...
    'cnn_gradients_display.m'};
for i = 1:length(otherFiles)
    fileMappings{end+1} = {otherFiles{i}, 'others'};
end

% Create 'others' folder if needed
if ~exist('others', 'dir')
    mkdir('others');
end

%% Move files
movedCount = 0;
skippedCount = 0;
errorCount = 0;
errors = {};

for i = 1:length(fileMappings)
    sourceFile = fileMappings{i}{1};
    targetFolder = fileMappings{i}{2};
    
    if ~exist(sourceFile, 'file')
        skippedCount = skippedCount + 1;
        if ~dryRun
            fprintf('  Skipped (not found): %s\n', sourceFile);
        end
        continue;
    end
    
    % Check if target folder exists
    if ~exist(targetFolder, 'dir')
        if ~dryRun
            mkdir(targetFolder);
            fprintf('  Created folder: %s\n', targetFolder);
        end
    end
    
    targetPath = fullfile(targetFolder, sourceFile);
    
    % Check if target already exists
    if exist(targetPath, 'file')
        if ~dryRun
            warning('Target already exists: %s', targetPath);
            response = input(sprintf('Overwrite %s? (y/n): ', sourceFile), 's');
            if ~strcmpi(response, 'y')
                fprintf('  Skipped: %s\n', sourceFile);
                skippedCount = skippedCount + 1;
                continue;
            end
        else
            fprintf('  Would skip (exists): %s -> %s\n', sourceFile, targetPath);
            skippedCount = skippedCount + 1;
            continue;
        end
    end
    
    if dryRun
        fprintf('  Would move: %s -> %s\n', sourceFile, targetPath);
        movedCount = movedCount + 1;
    else
        try
            [status, msg] = movefile(sourceFile, targetPath);
            if status
                fprintf('  Moved: %s -> %s\n', sourceFile, targetPath);
                movedCount = movedCount + 1;
            else
                error('Failed to move: %s\nError: %s', sourceFile, msg);
                errorCount = errorCount + 1;
                errors{end+1} = sprintf('%s: %s', sourceFile, msg);
            end
        catch ME
            errorCount = errorCount + 1;
            errors{end+1} = sprintf('%s: %s', sourceFile, ME.message);
            fprintf('  ERROR moving %s: %s\n', sourceFile, ME.message);
        end
    end
end

%% Summary
fprintf('\n=== MIGRATION SUMMARY ===\n');
if dryRun
    fprintf('DRY RUN - No files were actually moved\n');
    fprintf('To actually move files, run: migrate_files(false)\n\n');
end
fprintf('Files processed: %d\n', length(fileMappings));
fprintf('Moved: %d\n', movedCount);
fprintf('Skipped: %d\n', skippedCount);
if errorCount > 0
    fprintf('Errors: %d\n', errorCount);
    fprintf('\nErrors:\n');
    for i = 1:length(errors)
        fprintf('  %s\n', errors{i});
    end
end

%% Move .mat report files
fprintf('\n=== Moving .mat report files ===\n');
matReportFiles = {'cxr_annotation_organization_report.mat', ...
                  'cxr_organization_report.mat', ...
                  'cxr_simple_organization_report.mat'};

for i = 1:length(matReportFiles)
    if exist(matReportFiles{i}, 'file')
        targetPath = fullfile('results', 'reports', matReportFiles{i});
        if dryRun
            fprintf('  Would move: %s -> %s\n', matReportFiles{i}, targetPath);
        else
            try
                movefile(matReportFiles{i}, targetPath);
                fprintf('  Moved: %s -> %s\n', matReportFiles{i}, targetPath);
            catch ME
                fprintf('  ERROR: %s\n', ME.message);
            end
        end
    end
end

fprintf('\n=== MIGRATION COMPLETE ===\n');
if dryRun
    fprintf('\nTo actually move files, run:\n');
    fprintf('  migrate_files(false)\n');
end

end

