function organize_folder_structure()
%ORGANIZE_FOLDER_STRUCTURE Create organized folder structure and help migrate files
%   This script creates a proper folder structure for the research project
%   and provides a migration plan for organizing existing files.
%
%   Usage:
%   1. Run this script to create folder structure
%   2. Review the migration plan in FOLDER_MIGRATION_LOG.txt
%   3. Manually move files or use the provided helper functions

fprintf('=== FOLDER STRUCTURE ORGANIZATION ===\n\n');

%% Create folder structure
fprintf('Creating folder structure...\n');

% Source code folders
folders = {
    'src/training', ...
    'src/evaluation', ...
    'src/utils', ...
    'src/visualization', ...
    'src/loss_functions', ...
    'models/checkpoints', ...
    'models/final', ...
    'models/pretrained', ...
    'results/training', ...
    'results/evaluation', ...
    'results/ood', ...
    'results/comparisons', ...
    'results/figures', ...
    'results/reports', ...
    'docs/guides', ...
    'docs/analysis', ...
    'docs/papers', ...
    'scripts/data_preprocessing', ...
    'scripts/analysis', ...
    'config'
};

for i = 1:length(folders)
    folderPath = folders{i};
    if ~exist(folderPath, 'dir')
        mkdir(folderPath);
        fprintf('  Created: %s\n', folderPath);
    else
        fprintf('  Exists:  %s\n', folderPath);
    end
end

fprintf('\nFolder structure created successfully!\n\n');

%% Generate migration plan
fprintf('Generating migration plan...\n');
generate_migration_plan();

fprintf('\n=== ORGANIZATION COMPLETE ===\n');
fprintf('Review FOLDER_MIGRATION_LOG.txt for file migration plan\n');
fprintf('Use move_file_to_folder() helper function to migrate files\n');

end

function generate_migration_plan()
% Generate a detailed migration plan for all files

fid = fopen('FOLDER_MIGRATION_LOG.txt', 'w');
if fid == -1
    error('Could not create migration log file');
end

fprintf(fid, 'FOLDER MIGRATION PLAN\n');
fprintf(fid, '=====================\n\n');
fprintf(fid, 'Generated: %s\n\n', datestr(now));
fprintf(fid, 'Instructions:\n');
fprintf(fid, '1. Review this plan\n');
fprintf(fid, '2. Use move_file_to_folder() function to migrate files\n');
fprintf(fid, '3. Update any file paths in scripts after migration\n\n');
fprintf(fid, '%s\n\n', repmat('=', 1, 80));

%% Training scripts
fprintf(fid, 'TRAINING SCRIPTS -> src/training/\n');
fprintf(fid, '%s\n\n', repmat('-', 1, 80));
training_files = {
    'train_model_fixed_overfitting.m', ...
    'compare_loss_functions.m', ...
    'train_vgg16_gradcam.m', ...
    'train_vgg16_lime.m', ...
    'train_vgg16_lime_fixed.m', ...
    'train_vgg16_lime_memory_efficient.m', ...
    'train_vgg16_lime_precomputed.m', ...
    'training_with_precomputed_gradcam.m', ...
    'kriging_hyperparameter_optimization.m'
};
for i = 1:length(training_files)
    if exist(training_files{i}, 'file')
        fprintf(fid, '  %s\n', training_files{i});
    end
end
fprintf(fid, '\n');

%% Evaluation scripts
fprintf(fid, 'EVALUATION SCRIPTS -> src/evaluation/\n');
fprintf(fid, '%s\n\n', repmat('-', 1, 80));
evaluation_files = {
    'evaluate_with_tta.m', ...
    'evaluate_ood_performance.m', ...
    'evaluate_cam_ood.m', ...
    'evaluate_cam_ood_complete.m', ...
    'test_ood_cam_complete.m', ...
    'test_ood_full_cxr.m', ...
    'test_cam_ood_cxr.m', ...
    'test_vgg16_on_cxr.m'
};
for i = 1:length(evaluation_files)
    if exist(evaluation_files{i}, 'file')
        fprintf(fid, '  %s\n', evaluation_files{i});
    end
end
fprintf(fid, '\n');

%% Loss functions
fprintf(fid, 'LOSS FUNCTIONS -> src/loss_functions/\n');
fprintf(fid, '%s\n\n', repmat('-', 1, 80));
loss_files = {
    'custom_loss_gradcam_advanced.m', ...
    'custom_loss_gradcam_clean.m', ...
    'custom_loss_gradcam_comprehensive.m', ...
    'custom_loss_gradcam_optimized.m', ...
    'custom_loss_gradcam_segmentation_enhanced_fixed.m', ...
    'custom_loss_gradcam_soft_iou_kfold.m', ...
    'custom_loss_gradcam_training.m', ...
    'custom_loss_gradcam_with_mask_iou.m', ...
    'custom_loss_gradcam_with_mask_iou_fast.m', ...
    'Loss_grad_cam.m', ...
    'VGG_loss_lime_entropy.m', ...
    'Resnet50_Loss.m'
};
for i = 1:length(loss_files)
    if exist(loss_files{i}, 'file')
        fprintf(fid, '  %s\n', loss_files{i});
    end
end
fprintf(fid, '\n');

%% Visualization scripts
fprintf(fid, 'VISUALIZATION SCRIPTS -> src/visualization/\n');
fprintf(fid, '%s\n\n', repmat('-', 1, 80));
viz_files = {
    'visualize_gradcam.m', ...
    'generate_research_paper_visualizations.m', ...
    'create_publication_visualizations_fixed.m', ...
    'create_comprehensive_visualizations.m', ...
    'create_comprehensive_visualizations__.m', ...
    'create_key_visualizations.m', ...
    'run_visualizations.m', ...
    'test_visualization_generator.m'
};
for i = 1:length(viz_files)
    if exist(viz_files{i}, 'file')
        fprintf(fid, '  %s\n', viz_files{i});
    end
end
fprintf(fid, '\n');

%% Data preprocessing
fprintf(fid, 'DATA PREPROCESSING -> scripts/data_preprocessing/\n');
fprintf(fid, '%s\n\n', repmat('-', 1, 80));
preproc_files = {
    'organize_cxr_images.m', ...
    'organize_cxr_simple.m', ...
    'organize_cxr_with_annotations.m', ...
    'resize_and_copy_to_resized.m', ...
    'resize_and_organize_images.m', ...
    'precompute_gradcams.m', ...
    'create_roi_from_cxr_and_masks.m', ...
    'copy_masks_only.m', ...
    'remove_images_without_masks.m', ...
    'analyze_resized_folder.m'
};
for i = 1:length(preproc_files)
    if exist(preproc_files{i}, 'file')
        fprintf(fid, '  %s\n', preproc_files{i});
    end
end
fprintf(fid, '\n');

%% Analysis scripts
fprintf(fid, 'ANALYSIS SCRIPTS -> scripts/analysis/\n');
fprintf(fid, '%s\n\n', repmat('-', 1, 80));
analysis_files = {
    'segmentation_mask_similarity_metrics.m', ...
    'vgg16_cam_mask_similarity_metrics.m', ...
    'ssim_based_loss_on_precomputed_gradcam.m', ...
    'ssim_based_loss_on_precomputed_gradcam_2.m', ...
    'ssim_vgg_2.m', ...
    'diagnostic_test.m', ...
    'debug_gradcam.m', ...
    'debug_network.m', ...
    'diagnose_overfitting.m', ...
    'function ablation_and_ood_experiments.m', ...
    'function fast_kfold_segmentation_enhance.m', ...
    'vgg16_custom_loop.m', ...
    'vgg16_custom_loop_loss2.m', ...
    'vgg16_custom_loop_loss3.m', ...
    'vgg16_custom_loop_loss4.m', ...
    'vgg16_roi_entropy_custom_loop.m', ...
    'vgg16_lungs_test.m', ...
    'vgg16_cam_mask_similarity_metrics.m'
};
for i = 1:length(analysis_files)
    if exist(analysis_files{i}, 'file')
        fprintf(fid, '  %s\n', analysis_files{i});
    end
end
fprintf(fid, '\n');

%% Documentation
fprintf(fid, 'DOCUMENTATION -> docs/\n');
fprintf(fid, '%s\n\n', repmat('-', 1, 80));
fprintf(fid, 'GUIDES -> docs/guides/\n');
guide_files = {
    'TRAINING_RESULTS_ANALYSIS.md', ...
    'OOD_TEST_README.md', ...
    'KRIGING_OPTIMIZATION_README.md', ...
    'RESEARCH_PAPER_VISUALIZATIONS_README.md', ...
    'IMPROVE_OOD_ACCURACY_README.md', ...
    'IMPLEMENTATION_SUMMARY.md'
};
for i = 1:length(guide_files)
    if exist(guide_files{i}, 'file')
        fprintf(fid, '  %s\n', guide_files{i});
    end
end
fprintf(fid, '\n');

fprintf(fid, 'ANALYSIS REPORTS -> docs/analysis/\n');
analysis_docs = {
    'OVERFITTING_ANALYSIS.md', ...
    'ROC_AUC_ANALYSIS.md', ...
    'MEDICAL_IMAGE_AUGMENTATION.md', ...
    'DOMAIN_ADAPTATION_EXPLANATION.md', ...
    'TVERSKY_LOSS_IMPLEMENTATION.md', ...
    'Comprehensive_Kriging_Analysis.md', ...
    'kriging_optimization_analysis.md', ...
    'kriging_results_tables.md', ...
    'kriging_executive_summary.md'
};
for i = 1:length(analysis_docs)
    if exist(analysis_docs{i}, 'file')
        fprintf(fid, '  %s\n', analysis_docs{i});
    end
end
fprintf(fid, '\n');

fprintf(fid, 'PAPER DOCS -> docs/papers/\n');
paper_docs = {
    'methodology_1.qmd', ...
    'kriging_latex_format.tex', ...
    'latex_figure_descriptions.md', ...
    'RESEARCH_COMPLETION_PLAN.md', ...
    'FOLDER_STRUCTURE_PLAN.md'
};
for i = 1:length(paper_docs)
    if exist(paper_docs{i}, 'file')
        fprintf(fid, '  %s\n', paper_docs{i});
    end
end
fprintf(fid, '\n');

%% Models
fprintf(fid, 'MODELS -> models/\n');
fprintf(fid, '%s\n\n', repmat('-', 1, 80));
fprintf(fid, 'PRETRAINED -> models/pretrained/\n');
model_files = {
    'vgg16_finetuned_on_roi.mat', ...
    'vgg16_trained_on_roi.m', ...
    'custom_cnn_and_vgg16_gradcam_mask_iou.mat'
};
for i = 1:length(model_files)
    if exist(model_files{i}, 'file')
        fprintf(fid, '  %s\n', model_files{i});
    end
end
fprintf(fid, '\n');

%% Other files to review
fprintf(fid, 'FILES TO REVIEW MANUALLY:\n');
fprintf(fid, '%s\n\n', repmat('-', 1, 80));
other_files = {
    'custom.m', ...
    'custom.asv', ...
    'custom_lime.m', ...
    'custom_lime.asv', ...
    'custom_roi.m', ...
    'custom_vgg16_transfer_gradcam.m', ...
    'cnn_lime.asv', ...
    'cnn_gradients_display.m', ...
    'code_1.m', ...
    'fast_simple_test.m', ...
    'fine_tuned_lime.m', ...
    'improve_ood_accuracy.m', ...
    'simple_fixed_comprehensive.m', ...
    'block_diagram_vgg16.m', ...
    'workflow.m', ...
    'workflow_diagram.m', ...
    'run_diagram.m', ...
    'run_resize_script.m', ...
    'custom_loss_gradcam_wireframe.svg', ...
    'cxr_*.mat', ...
    '*.asv'  % MATLAB autosave files
};
fprintf(fid, 'These files may need manual categorization:\n');
for i = 1:length(other_files)
    if exist(other_files{i}, 'file') || ~isempty(dir(other_files{i}))
        fprintf(fid, '  %s\n', other_files{i});
    end
end

fprintf(fid, '\n\n');
fprintf(fid, 'NOTES:\n');
fprintf(fid, '- Keep input/ and output/ folders as they are\n');
fprintf(fid, '- results/ folder structure will be created automatically\n');
fprintf(fid, '- Update file paths in scripts after migration\n');
fprintf(fid, '- Consider adding src/ to MATLAB path\n');

fclose(fid);
fprintf('Migration plan saved to: FOLDER_MIGRATION_LOG.txt\n');

end

function move_file_to_folder(fileName, targetFolder)
%MOVE_FILE_TO_FOLDER Helper function to move files to organized folders
%   move_file_to_folder('train_model_fixed_overfitting.m', 'src/training')
%
%   This function safely moves files and creates backup if needed

if ~exist(fileName, 'file')
    warning('File not found: %s', fileName);
    return;
end

if ~exist(targetFolder, 'dir')
    mkdir(targetFolder);
    fprintf('Created folder: %s\n', targetFolder);
end

targetPath = fullfile(targetFolder, fileName);

if exist(targetPath, 'file')
    warning('Target file already exists: %s', targetPath);
    response = input('Overwrite? (y/n): ', 's');
    if ~strcmpi(response, 'y')
        fprintf('Skipped: %s\n', fileName);
        return;
    end
end

% Move file
[status, msg] = movefile(fileName, targetPath);
if status
    fprintf('Moved: %s -> %s\n', fileName, targetPath);
else
    error('Failed to move file: %s\nError: %s', fileName, msg);
end

end

